# Generated by Django 5.2.17 on 2026-09-20 12:13

import django
from django.db import migrations, models


def _promo_use_count_constraint():
    bound = models.Q(("use_count__lte", models.F("max_uses")))
    kwargs = {"name": "promo_use_count_lte_max_uses"}
    if django.VERSION >= (5, 1):
        return models.CheckConstraint(condition=bound, **kwargs)
    return models.CheckConstraint(check=bound, **kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="use_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="promocode",
            constraint=_promo_use_count_constraint(),
        ),
    ]
